#!/usr/bin/env python3
"""Compatibility entry point; new integrations should import the package."""
from importlib import import_module
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from obsidian_graphify.cli import main
from obsidian_graphify.config import VaultContext, use_vault

_OWNERS = {'RELATION_FIELDS': 'model',
 'CLAIM_REF_FIELDS': 'model',
 'COMMON_WIKI_FIELDS': 'model',
 'SOURCE_FIELDS': 'model',
 'CLAIM_FIELDS': 'model',
 'WIKI_FIELDS': 'model',
 'VALID_TYPES': 'model',
 'VALID_STATUSES': 'model',
 'VALID_SUPPORT_STATES': 'model',
 'VALID_VERIFICATION_STATES': 'model',
 'VALID_CLAIM_STATUSES': 'model',
 'STANDALONE_CLAIM_GRAPH_ROLE': 'model',
 'MARKDOWN_EXTENSIONS': 'model',
 'RAW_EXCLUDED_DIRS': 'model',
 'IGNORED_FILENAMES': 'model',
 'VIDEO_EXTENSIONS': 'media.protocol',
 'MEDIA_COMPILE_MODES': 'media.protocol',
 'VISUAL_MODE': 'media.protocol',
 'DEFAULT_VISUAL_MAX_INTERVAL_SECONDS': 'media.protocol',
 'DEFAULT_VISUAL_MAX_FRAMES': 'media.protocol',
 'VISUAL_OCR_NOISE_PATTERNS': 'media.protocol',
 'Note': 'model',
 'RawItem': 'model',
 'Edge': 'model',
 'LookupUnit': 'model',
 'LookupMatch': 'model',
 'RelatedMatch': 'model',
 'MediaProbe': 'media.protocol',
 'VisualRegionRecord': 'media.protocol',
 'VisualAnchorRecord': 'media.protocol',
 'VisualFrameRecord': 'media.protocol',
 'VisualCompileArtifact': 'media.protocol',
 'parse_args': 'cli',
 'main': 'cli',
 'load_vault': 'vault',
 'collect_knowledge_notes': 'vault',
 'collect_raw_items': 'vault',
 'collect_markdown_notes': 'vault',
 'build_node_specs': 'vault',
 'build_alias_map': 'vault',
 'collect_processed_raw_refs': 'vault',
 'extract_scope_refs': 'commands.scope',
 'resolve_scope': 'commands.scope',
 'expand_scope_paths': 'commands.scope',
 'command_scope': 'commands.scope',
 'command_scan': 'commands.maintenance',
 'command_changes': 'commands.maintenance',
 'command_lookup': 'commands.lookup',
 'command_impact': 'commands.maintenance',
 'command_status': 'commands.maintenance',
 'validate_notes': 'commands.lint',
 'command_lint': 'commands.lint',
 'command_export': 'commands.maintenance',
 'command_compile_media': 'media.transfer_platform',
 'LocalVisualCompileBackend': 'media.visual',
 'compile_video_visual_raw_item': 'media.visual',
 'build_edges': 'graph',
 'edge_counts': 'graph',
 'adjacency': 'graph',
 'find_impacted_notes': 'graph',
 'build_graph_summary': 'graph',
 'build_graphml': 'graph',
 'build_link_manifest': 'graph',
 'build_file_snapshot': 'vault',
 'compare_manifests': 'graph',
 'load_markdown': 'parsing',
 'split_frontmatter': 'parsing',
 'parse_frontmatter': 'parsing',
 'parse_scalar': 'parsing',
 'find_standalone_claim_paths': 'graph',
 'extract_wikilinks': 'parsing',
 'extract_section': 'parsing',
 'extract_top_level_sections': 'parsing',
 'extract_callout': 'parsing',
 'body_preview': 'parsing',
 'route_text': 'commands.lookup',
 'knowledge_lookup_text': 'commands.lookup',
 'claim_lookup_text': 'commands.lookup',
 'build_lookup_units': 'commands.lookup',
 'lookup_section_priority': 'commands.lookup',
 'best_lookup_match': 'commands.lookup',
 'build_related_matches': 'commands.lookup',
 'infer_route_clusters': 'commands.lookup',
 'note_in_clusters': 'commands.lookup',
 'tokenize_query': 'commands.lookup',
 'score_match': 'commands.lookup',
 'edge_weight': 'commands.lookup',
 'infer_media_compile_mode': 'media.paths',
 'compiled_visual_note_path': 'media.paths',
 'compiled_visual_asset_dir': 'media.paths',
 'compiled_visual_ocr_regions_path': 'media.paths',
 'visual_frame_filename': 'media.visual',
 'format_timestamp_token': 'media.visual',
 'format_timestamp': 'media.visual',
 'normalize_visual_timestamps': 'media.visual',
 'probe_media_with_ffprobe': 'media.visual',
 'detect_visual_timestamps': 'media.visual',
 'extract_frame_with_ffmpeg': 'media.visual',
 'normalize_ocr_lines': 'media.visual',
 'normalize_ocr_regions': 'media.visual',
 'parse_ocr_region_item': 'media.visual',
 'normalize_region_bbox': 'media.visual',
 'is_number': 'media.visual',
 'filter_visual_ocr_lines': 'media.visual',
 'filter_visual_ocr_regions': 'media.visual',
 'normalize_ocr_text': 'media.visual',
 'is_visual_ocr_noise': 'media.visual',
 'maybe_visual_ocr_noise': 'media.visual',
 'default_visual_frame_fingerprint': 'media.visual',
 'get_visual_frame_fingerprint': 'media.visual',
 'build_visual_anchor_records': 'media.visual',
 'build_visual_ocr_sidecar': 'media.visual',
 'render_visual_source_markdown': 'media.visual',
 'detect_visual_doc_lang': 'media.visual',
 'has_cjk_text': 'media.visual',
 'visual_keywords_for_frame': 'media.visual',
 'format_timestamp_span': 'media.visual',
 'require_executable': 'media.visual',
 'resolve_transfer_platform_executable': 'media.transfer_platform',
 'infer_title': 'parsing',
 'infer_source_type': 'parsing',
 'infer_knowledge_kind': 'parsing',
 'candidate_keys': 'refs',
 'normalize_ref': 'refs',
 'dedupe_preserve_order': 'refs',
 'sanitize_filename': 'media.paths',
 'resolve_reference': 'refs',
 'as_string': 'utils',
 'listify': 'utils',
 'to_float': 'utils',
 'is_stale': 'utils',
 'load_json': 'utils',
 'write_text': 'utils'}

def __getattr__(name):
    if name in _OWNERS:
        return getattr(import_module("obsidian_graphify." + _OWNERS[name]), name)
    raise AttributeError(name)


if __name__ == "__main__":
    raise SystemExit(main())
